spring:
  application:
    name: kafka
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/task
    username: root
    password: 123456

server:
  port: 9091

logging:
  file:
    name: logs/log
#日志配置文件路径
#  config: classpath:logback.xml
mybatis:
  mapper-locations: classpath:mapping/*.xml
